language: scala

scala:
   - 2.10.4
   - 2.11.7
   - 2.12.2

env:
- JDK=oraclejdk8
- JDK=oraclejdk7
- JDK=openjdk7

before_script:
    - jdk_switcher use $JDK

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.2
      env: JDK=oraclejdk7
    - scala: 2.12.2
      env: JDK=openjdk7
